# Basic appveyor configuration : CodeCakeBuilder does the job.
version: build{build}
branches:
  only:
  - master
  - develop
environment:
  NUGET_API_KEY:
    secure: 6Mkq9j837AfVCmTdVG83j/UW3B9KuCQxa3egC4j4X0GRaXWyRhoJUnKe3Xsvk9jS
install:
- ps: CodeCakeBuilder\Bootstrap.ps1
build_script:
- CodeCakeBuilder\bin\Release\CodeCakeBuilder.exe -nointeraction
test: off